{% set name = "seismon" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/seismon-{{ version }}.tar.gz
  sha256: 8cac33d5d763fdaabf04b12b319820bc09a7091c9e1da38599c93c0b2820424d

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - arrow
    - astropy
    - flask-caching
    - flask-login
    - flask-sqlalchemy
    - flask-wtf
    - gwpy
    - lxml
    - matplotlib-base >=2.2.0
    - numpy >=1.7.1
    - obspy
    - passlib
    - python
    - redis-py
    - scipy >=0.12.1
    - simplejson
    - sqlalchemy

test:
  imports:
    - seismon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gwdetchar/seismon/
  summary: A python package for mitigating the effects of earthquakes on GW detectors
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mcoughlin
